# Generated by Django 4.1.7 on 2023-04-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='category',
        ),
    ]
